version: "3"

services:
  db:
    image: postgres:latest
    container_name: gamersays_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"

  be:
    container_name: gamersays_be
    build: backend
    command: bash -c "cd backend && pip freeze && python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx_fe
    build: frontend
    ports:
      - '80:80'